// Generated by CoffeeScript 1.7.1

/*
 * Gouda
 * Authors:
 * 	Kenneth Jackson (whoiskenjackson)
 * 	Wyatt Meade (WyattMeade)
 */

(function() {
  var Gouda;

  Gouda = function() {
    var bindEvents, init, renderGuide, renderTemplates;
    this.opt = {
      scope: $("section"),
      model: iconData,
      templates: Handlebars.templates
    };
    renderGuide = function(icon) {
      var model;
      model = {
        icon: "" + icon + ""
      };
      return this.$el.find(".guide").html(this.opt.templates["guide"](model));
    };
    renderTemplates = function() {
      this.$el.find("article").append(this.opt.templates["main"]);
      return this.$el.find(".icons-container").append(this.opt.templates["iconsList"](this.opt.model));
    };
    bindEvents = function() {
      return $(document).on("click", "[data-icon]", function(e) {
        var icon;
        e.preventDefault();
        icon = $(this).data("icon");
        return renderGuide(icon);
      });
    };
    init = function() {
      this.$el = opt.scope;
      renderTemplates();
      return bindEvents();
    };
    return init();
  };

  Gouda();

}).call(this);
